### ISSUE TITLE
DEMAND FOR NEW UI CHNAGES

### ISSUE THREAD

**Issue by aryanbuilds** [SDC-USAR/ArtiGenius-AI#16]
## Feature Request ✨

**Description:**

A change is UI is necessary as curently it has little to no interaction. Basically way to minimal.

**Use Case:**
As a new Ui will be more interactive and interesting.

**Proposed Solution:**
I'll be redesigning some ui And change in FOnt style and try to keep it minimal at hte same time. 

**Additional Information:**
I'll not be modifying unnecessary things in Ui just basic ones which will be soothing to your eyes.

## Checklist

- [x] Create a new basic Ui.
- [x] Correct some color scheme, Font choices and design.
- [x] Assign this issue .

**Comment by rahmlad-aramide** [comment]
I'll like to be the one to implement this, meanwhile, I want clarification on what was meant on UI as stated here, is it like a UI design maybe on Figma or the Normal interface redesign in the codebase? Meanwhile, I'll suggest you create separate issues for both so that it can have a professional touch and at the same time ensure uniformity when this app is scaling up, the additional features will just be getting built on top of the one already established

**Comment by rahmlad-aramide** [comment]
> I'll like to be the one to implement this, meanwhile, I want clarification on what was meant on UI as stated here, is it like a UI design maybe on Figma or the Normal interface redesign in the codebase? Meanwhile, I'll suggest you create separate issues for both so that it can have a professional touch and at the same time ensure uniformity when this app is scaling up

If you agree to the suggestion, I have a UI/UX designer that'll be interested in doing that, otherwise I'll handle it alone, looking forward to receiving a response from you
cc: @ayuugoyal @wountv
